services:
  db:
    container_name: observium-db
    image: mariadb:10.5.2
    restart: unless-stopped
    env_file:
      - .env_mysql
    volumes:
      - observium-db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    mem_limit: 1000m
    mem_reservation: 300m

  app:
    container_name: observium-app
    depends_on:
      - db
    image: voltagepark/observium:latest
    restart: unless-stopped
    env_file:
      - .env_observium
    volumes:
      - observium-config:/config
      - observium-data:/opt/observium
    ports:
      - "80:80"
    mem_limit: 1000m
    mem_reservation: 600m

volumes:
  observium-db-data:
    driver_opts:
      type: none
      device: /mnt/netops/observability/observium/db
      o: bind

  observium-config:
    driver_opts:
      type: none
      device: /mnt/netops/observability/observium/config
      o: bind

  observium-data:
    driver_opts:
      type: none
      device: /mnt/netops/observability/observium/observium
      o: bind
